# Get editor completions based on the config schema
# Use custom format
#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$directory$rust$package
#[â””â”€>](bold green) """
command_timeout = 1000


[conda]
ignore_base = false
#symbol = "ğŸ "
